#+TITLE: DATA
#+AUTHOR: Logan Jackson
#+DATE: \today

* Introduction
The fundamental structure of the data that we are presenting is, represented by a tensor of rank n.

* 2D Brain Data
In 2 dimensions the cross sections of a brain can be, presented as a matrix (2 tensor) $W \times H$ but in order to pass
this information to our model we usually need to also present an empty $B$ dimension so that the model
understands how many images we are passing in this case we're only passing a single image to the model so $B=1$
by nesting the image into a single batch this raises the rank of the tensor by one making the resulting data a 3 tensor
represented by a tuple $(B, H, W)$.

* 3D Brain Data
3D brain data is, represented similar to our 2D brain data but instead of $B=1$ it's the number of slices that make
up the volume of the brain, a typical brain scan may contain anywhere from 180-300 images. In addition to this both
2D and 3D Brain data can also contain a $C$ dimension where $C$ represents the number of channels in the image
for example a typical RGB picture contains 3 channels but in the case of our data we typically stick to 1 channel.
When passing a channel in addition to the batch, height, and width there is now a channel raising the rank of the tensor
by one again, in this case we can represent the shape of our tensor with a 4 tuple $(B, H, W, C)$

* 4D Brain Data
Intuitively as the dimensions go up you may think about how the data is, represented in real life. In the case of
2D brain data this would be a cross section of the brain and in the case of 3D brain data this would be the whole
volume of the brain. With 4D brain data you can think about this as a video of the whole brain over time, instead
of a single whole brain volume you now have many brain volumes and can see how these brain volumes are changing
over time this is particularly useful for extracting connectome data which will be, discussed later in the Autism
section. In addition the tensor representation of the brain raises by one again to include $T$ or the number of
brains. In our data $T = 180$ for Autism the shape of this tensor can be show with a 5 tuple $(T, B, H, W, C)$
